# -*- coding: utf-8 -*-
"""Case Study - Student.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1hfvbjNLXkrhGbohnaEvV3n5LqzV6twJD

# 📊 Student Outcomes Analysis

**Company:** EduPulse Analytics
**Role:** Junior Data Analyst

## 🏫 Scenario

The administration at **EduPulse University** is concerned about declining graduation rates. They have provided you with a dataset to identify why students are struggling and how attendance correlates with final grades.

---

## 🎯 Your Tasks

### 1️⃣ Calculate the Average Marks

* Compute the **average marks** of all students in the dataset.

---

### 2️⃣ High Performers Analysis

* Filter the dataset to determine **how many students scored above 75 marks**.

---

### 3️⃣ Correlation Analysis

* Analyze whether **higher attendance leads to better marks**.
* Calculate the **correlation coefficient** between Attendance and Marks.
* Briefly interpret the result.

---

### 4️⃣ Feature Engineering

* Create a new column called **`Pass`** where:

```
Pass = True  if Marks >= 50  
Pass = False if Marks < 50
```

---

### 5️⃣ Summary Statistics

* Count the total number of:

  * ✅ Passes
  * ❌ Fails

---

### 6️⃣ Visualization

* Create a **distribution plot (histogram)** of student marks.
* Add appropriate:

  * Title
  * Axis labels
  * Grid (optional)

---

## 📌 Expected Outcome

By completing this analysis, you should be able to:

* Understand student performance trends
* Identify high-performing students
* Determine the relationship between attendance and marks
* Generate meaningful summary statistics
* Visualize the distribution of academic performance

---
"""

# 1. Average
df['marks'].mean()

# 3. Correlation
df['attendance'].corr(df['marks'])

# 4. New Column
df['Pass'] = df['marks'] >= 50

# 6. Plotting
import seaborn as sns
sns.histplot(df['marks'], kde=True)

import pandas as pd

df = pd.read_csv("/content/student_performance_dataset_dirty.csv")

df

df.info()

df.describe()

df["Marks"].mean()

df["Attendance_Percentage"].mean()

df["Age"].mean()

df.isnull()

df.isnull().sum()

df

df.duplicated()

df.duplicated().sum()

df[df.duplicated()]

df = df.drop_duplicates()

df

df[df["Age"] > 30]

df.isnull().sum()

df.dropna()

df

df["Marks"] = df["Marks"].fillna(df["Marks"].mean())

df

df["Name"] = df["Name"].fillna("Abhinav")

df

df[df.duplicated()]

df["Age"] = df["Age"].fillna(df["Age"].mean())

df

df[df["Age"] > 30]

df.loc[df["Age"] > 30 , "Age"] = df["Age"].mean()

df

df.loc[df["Marks"] < 0 , "Marks"] = df["Marks"].mean()

df.loc[df["Marks"] < 0 , "Marks"] = 0

df

df = df[df["Marks"] >= 0]

df.loc[df["Attendance_Percentage"] > 100 , "Attendance_Percentage"] = df["Attendance_Percentage"].mean()

df





import pandas as pd

# Load the dataset
df = pd.read_csv("student_performance_dataset_2_89f6da2c.csv")

# Calculate the average of the marks column
average_marks = df["Marks"].mean()

print(f"Average marks: {average_marks:.2f}")